### ISSUE TITLE
Add option for multiline-arrays

### ISSUE THREAD

**Issue by timpulver** [jakwings/tomlify-j0.4#1]
Would be great if tomlify supports arrays with line breaks (compliant with [TOML 4.0](https://github.com/toml-lang/toml#user-content-example)), e.g.

```
# Line breaks are OK when inside arrays
hosts = [
  "alpha",
  "omega"
]
```

**Comment by iology** [comment]
I regret that tomlify doesn't completely match the behavior of `JSON.stringify`. Because it is quite hard to use a `replacer` function to implement this printing style, so I may adopt this multi-line style in v2.0.0, without providing an option.

**Comment by iology** [comment]
There is one exception:

while tomlify({a:{b:{c:[[],[]]}}}, null, **2**) gives

```
[a]

  [a.b]
  c = [
    [],
    []
  ]
```

should tomlify({a:{b:{c:[[],[]]}}}, null, **0**) gives

```
[a]

[a.b]
c = [
  [],
  []
]
```

or

```
[a]

[a.b]
c = [[], []]
```

or just indent array literals, not the whole sections?

**Comment by timpulver** [comment]
For me the latter makes most sense when indentation is set to `0`.

**Comment by iology** [comment]
Ok, now have a try with v2.0.0: <https://jakwings.github.io/tomlify-j0.4/demo/>

```javascript
tomlify({a:{b:{c:[[],[]]}}}, null, 0);
//[a]
//
//[a.b]
//c = [[], []]

tomlify({a:{b:{c:[[],[]]}}}, null, 2);
//[a]
//
//  [a.b]
//  c = [
//    [],
//    []
//  ]

tomlify([
  {pos: [0, 0], sop: [1, 1]},
  {matrix: [[6, 7, 2], [1, 5, 9], [8, 3, 4]]}
], null, 2);
//[
//  {pos = [0.0, 0.0], sop = [1.0, 1.0]},
//  {matrix = [[6.0, 7.0, 2.0], [1.0, 5.0, 9.0], [8.0, 3.0, 4.0]]}
//]
```

[Changelog here.](https://github.com/jakwings/tomlify-j0.4/blob/5b6b191004f3c239f859da0954a1021fd0a874db/CHANGELOG.md)

**Comment by iology** [comment]
v2.0.0 is already published.

**Comment by timpulver** [comment]
Output looks much better now, thanks!
